name: ğŸ› ï¸ Build & ğŸš€ Deploy Greenbone

on:
    workflow_dispatch:

jobs:
    deploy:
        name: ğŸ” Deploy Greenbone
        runs-on: self-hosted

        steps:
            - name: ğŸ“¥ Checkout
              uses: actions/checkout@v4

            - name: ğŸ³ Reiniciar entorno Greenbone
              run: |
                cd apps/greenbone/config
                docker compose down
                docker compose pull
                docker compose up -d
